
import React, { useEffect, useRef, useCallback } from 'react';
import { CreatorStudioProject, HistoryItem, ImageFile } from '../types';
import { analyzeStyleImage, translateText, generateImage, editImage } from '../services/geminiService';
import { resizeImage } from '../utils';
import CustomizationPanel from './CustomizationPanel';
import ImageWorkspace from './ImageWorkspace';
import PromptEditor, { PromptSuggestions } from './PromptEditor';
import HistoryPanel from './HistoryPanel';
import ResultDisplay from './ResultDisplay';
import ImageUploader from './ImageUploader';

interface CreatorStudioProps {
  project: CreatorStudioProject;
  setProject: React.Dispatch<React.SetStateAction<CreatorStudioProject>>;
}

const CreatorStudio: React.FC<CreatorStudioProps> = ({
  project,
  setProject,
}) => {
  
  const translateTimeoutRef = useRef<number | null>(null);
  const translationRequestCounter = useRef(0);

  const updateActiveProjectState = useCallback((updater: (projectDraft: CreatorStudioProject) => void) => {
    setProject(currentProject => {
      const projectToUpdate = { ...currentProject };
      updater(projectToUpdate);
      return projectToUpdate;
    });
  }, [setProject]);

  // Analyze style image when it changes for the active project
  useEffect(() => {
    // Only analyze if we have an image, no description yet, aren't currently analyzing, and have no prior error.
    if (project?.styleImage && !project.styleDescription && !project.isAnalyzingStyle && !project.error) {
      const getStyleDescription = async () => {
        updateActiveProjectState(p => { 
          p.isAnalyzingStyle = true;
          p.error = null;
        });
        try {
          const description = await analyzeStyleImage(project.styleImage as ImageFile);
          updateActiveProjectState(p => { p.styleDescription = description; });
        } catch (err) {
          console.error(err);
          updateActiveProjectState(p => {
            p.error = err instanceof Error ? err.message : "Could not analyze the style image.";
            p.styleDescription = null;
          });
        } finally {
          updateActiveProjectState(p => { p.isAnalyzingStyle = false; });
        }
      };
      getStyleDescription();
    } else if (!project?.styleImage && project?.styleDescription) {
      // If image was removed but description remains, clear it
      updateActiveProjectState(p => { p.styleDescription = null; });
    }
  }, [
    project?.id,
    project?.styleImage, 
    project?.styleDescription,
    project?.isAnalyzingStyle,
    project?.error,
    updateActiveProjectState
  ]);

  // Generate prompt automatically based on active project state, if not manually edited
  useEffect(() => {
    if (!project || !project.isPromptAutoGenerated) {
      return;
    }
    
    const { productImages, styleImage, options, isAnalyzingStyle, styleDescription } = project;
    
    if (productImages.length === 0 && !styleImage) {
      if(project.prompt !== '') {
          updateActiveProjectState(p => { p.prompt = ''; });
      }
      return;
    }

    let newPrompt = `Generate a high-resolution, professional photograph`;
    if (productImages.length > 0) {
      newPrompt += ` of the subject in the provided image${productImages.length > 1 ? 's' : ''}`;
    }
    newPrompt += `.

Key requirements:
- Lighting: Illuminate the scene with a ${options.lightingStyle} style. The lighting should be flattering and highlight the subject's details.
- Camera Perspective: Capture the subject from a ${options.cameraPerspective}.
- Background: The background should be clean, non-distracting, and complementary to the subject. A subtle, high-end studio setting is preferred.
- Overall Mood: The image should feel premium, clean, and aspirational.`;

    if (styleImage) {
      if (isAnalyzingStyle) {
          newPrompt += `\n\n- Style Reference: Analyzing the provided style reference image...`;
      } else if (styleDescription) {
          newPrompt += `\n\n- Style Reference: Strictly adhere to the aesthetic of the provided style reference image, which has a ${styleDescription}. The goal is to make the subject look as if it belongs in the same visual world.`;
      } else {
            newPrompt += `\n\n- Style Reference: Strictly adhere to the aesthetic, color palette, texture, and overall mood of the provided style reference image. The goal is to make the subject look as if it belongs in the same visual world as the style reference.`;
      }
    }
    
    if(project.prompt !== newPrompt) {
        updateActiveProjectState(p => { p.prompt = newPrompt; });
    }
  }, [
    project?.id,
    project?.isPromptAutoGenerated,
    project?.productImages, 
    project?.styleImage, 
    project?.options, 
    project?.isAnalyzingStyle, 
    project?.styleDescription,
    updateActiveProjectState
  ]);

  // Auto-translate prompt if it contains Arabic
  useEffect(() => {
    const arabicRegex = /[\u0600-\u06FF]/;
      
    if (!project || project.isPromptAutoGenerated) {
        if (project?.translatedPrompt || project?.isTranslating) {
            updateActiveProjectState(p => { 
                p.translatedPrompt = null;
                p.isTranslating = false;
            });
        }
        return;
    }

    if (translateTimeoutRef.current) {
        clearTimeout(translateTimeoutRef.current);
    }

    const promptToTranslate = project.prompt;

    if (!arabicRegex.test(promptToTranslate) || !promptToTranslate.trim()) {
        if (project.translatedPrompt || project.isTranslating) {
            updateActiveProjectState(p => {
                p.translatedPrompt = null;
                p.isTranslating = false;
            });
        }
        return;
    }

    translateTimeoutRef.current = window.setTimeout(async () => {
        translationRequestCounter.current += 1;
        const currentRequestId = translationRequestCounter.current;
        
        updateActiveProjectState(p => {
            p.isTranslating = true;
            p.error = null;
        });

        try {
            const translated = await translateText(promptToTranslate);
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => {
                    if (p.prompt === promptToTranslate) {
                        p.translatedPrompt = translated;
                    }
                });
            }
        } catch (err) {
            console.error(err);
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => {
                    p.error = err instanceof Error ? err.message : 'Translation failed.';
                });
            }
        } finally {
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => {
                   p.isTranslating = false;
                });
            }
        }
    }, 700);

  }, [project?.prompt, project?.isPromptAutoGenerated, updateActiveProjectState]);
  
  const handleGenerate = useCallback(async () => {
    if (!project || !project.prompt) {
      updateActiveProjectState(p => { p.error = 'Please write a prompt to generate an image.'; });
      return;
    }
    const currentPrompt = project.prompt;

    updateActiveProjectState(p => {
        p.isLoading = true;
        p.error = null;
        p.generatedImage = null;
    });

    try {
      const result = await generateImage(project.productImages, project.prompt, project.styleImage);
      updateActiveProjectState(p => {
          p.generatedImage = result;
          const newHistoryItem: HistoryItem = { image: result, prompt: currentPrompt };
          p.history = [newHistoryItem, ...p.history];
      });
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => { 
        p.error = err instanceof Error ? err.message : 'An unknown error occurred during image generation.';
      });
    } finally {
      updateActiveProjectState(p => { p.isLoading = false; });
    }
  }, [project, updateActiveProjectState]);

  const handleImageEdit = useCallback(async () => {
    if (!project?.generatedImage || !project.editPrompt) {
      updateActiveProjectState(p => { p.error = 'Please enter an edit instruction.'; });
      return;
    }
    
    const { generatedImage, editPrompt } = project;

    updateActiveProjectState(p => {
        p.isEditing = true;
        p.error = null;
    });

    try {
      const result = await editImage(generatedImage, editPrompt);
      updateActiveProjectState(p => {
          p.generatedImage = result;
          const newHistoryItem: HistoryItem = { image: result, prompt: editPrompt };
          p.history = [newHistoryItem, ...p.history];
          p.editPrompt = ''; // Clear prompt after success
      });
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => { 
        p.error = err instanceof Error ? err.message : 'An unknown error occurred during image editing.';
      });
    } finally {
      updateActiveProjectState(p => { p.isEditing = false; });
    }
  }, [project, updateActiveProjectState]);


  const handleFileUpload = (updater: (files: ImageFile[]) => void, target: 'product' | 'style') => async (files: File[]) => {
      if (!files || files.length === 0) return;

      updateActiveProjectState(p => {
        p.uploadingTarget = target;
        p.error = null;
      });
      let currentError: string | null = null;
      
      const filePromises = files.map(file => {
          return new Promise<ImageFile | null>(async (resolve) => {
              if (!file.type.startsWith('image/')) {
                  if(!currentError) currentError = `File '${file.name}' is not a supported image type.`;
                  resolve(null);
                  return;
              }

              try {
                  const resizedFile = await resizeImage(file, 2048, 2048);
                  const reader = new FileReader();
                  reader.onloadend = () => {
                      const base64String = reader.result as string;
                      resolve({
                          base64: base64String.split(',')[1],
                          mimeType: resizedFile.type,
                          name: resizedFile.name
                      });
                  };
                  reader.onerror = () => {
                      if(!currentError) currentError = `Error reading file '${resizedFile.name}'.`;
                      resolve(null);
                  };
                  reader.readAsDataURL(resizedFile);
              } catch (err) {
                  console.error(`Error processing ${file.name}:`, err);
                  if (!currentError) currentError = `Could not process file '${file.name}'.`;
                  resolve(null);
              }
          });
      });

      const results = await Promise.all(filePromises);

      const validImages = results.filter((img): img is ImageFile => img !== null);
      if (validImages.length > 0) {
          updater(validImages);
      }

      updateActiveProjectState(p => {
        p.error = currentError;
        p.uploadingTarget = null;
      });
  };
  
  const handleSetPrompt = (prompt: string) => updateActiveProjectState(p => {
    p.prompt = prompt;
    p.isPromptAutoGenerated = false;
  });

  const handleResetPrompt = useCallback(() => {
    updateActiveProjectState(p => {
        p.isPromptAutoGenerated = true;
    });
  }, [updateActiveProjectState]);

  const handleSetStyleImage = (image: ImageFile | null) => updateActiveProjectState(p => { 
    p.styleImage = image; 
    // Clear style description and error to trigger fresh analysis or clear state
    p.styleDescription = null;
    p.error = null;
  });
  
  const handleSingleFileUpload = handleFileUpload(files => handleSetStyleImage(files[0]), 'style');
  const handleMultipleFilesUpload = handleFileUpload(files => updateActiveProjectState(p => { p.productImages = [...p.productImages, ...files]; }), 'product');

  const handleRemoveProductImage = (indexToRemove: number) => {
    updateActiveProjectState(p => {
      p.productImages = p.productImages.filter((_, index) => index !== indexToRemove);
    });
  };
  
  const handleUpdateProductImage = (indexToUpdate: number, newImage: ImageFile) => {
    updateActiveProjectState(p => {
        const newImages = [...p.productImages];
        newImages[indexToUpdate] = newImage;
        p.productImages = newImages;
    });
  };

  const handleRemoveStyleImage = () => {
    updateActiveProjectState(p => {
      p.styleImage = null;
      p.styleDescription = null;
      p.error = null;
    });
  };
  
  const handleUpdateStyleImage = (index: number, newImage: ImageFile) => {
       // Since style is single image, index is always 0
       updateActiveProjectState(p => {
          p.styleImage = newImage;
          p.styleDescription = null; // Re-analyze needed
       });
  };

  const handleHistorySelectImage = (image: ImageFile) => {
    updateActiveProjectState(p => { p.generatedImage = image; });
  };
  
  const handleUseTranslation = (translatedText: string) => {
    updateActiveProjectState(p => {
      p.prompt = translatedText;
      p.isPromptAutoGenerated = false;
      p.translatedPrompt = null;
      p.isTranslating = false;
    });
  };

  if (!project) {
    return (
      <div className="flex-grow w-full flex flex-col items-center justify-center">
        <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-[var(--color-accent)]"></div>
      </div>
    );
  }

  return (
    <main className="w-full grid grid-cols-1 lg:grid-cols-2 gap-6 pt-4 pb-12 items-start">
        {/* --- LEFT COLUMN: INPUTS --- */}
        <div className="flex flex-col gap-4 order-1">
            
            {/* 1. Upload Area (Side-by-Side) */}
            <div className="grid grid-cols-2 gap-4 mb-6">
                {/* Product Image */}
                <div className="glass-card p-3 rounded-2xl flex flex-col gap-2 items-center">
                    <h3 className="text-sm font-bold text-[var(--color-text-medium)] text-center">Upload Image(s)</h3>
                    <div className="w-full max-w-[200px]">
                        <ImageWorkspace
                            productImages={project.productImages}
                            onProductImagesUpload={handleMultipleFilesUpload}
                            onProductImageRemove={handleRemoveProductImage}
                            isUploading={project.uploadingTarget === 'product'}
                            onProductImageUpdate={handleUpdateProductImage}
                        />
                    </div>
                </div>

                {/* Style Reference */}
                <div className="glass-card p-3 rounded-2xl flex flex-col gap-2 items-center">
                    <h3 className="text-sm font-bold text-[var(--color-text-medium)] text-center">Style Ref</h3>
                    <div className="w-full max-w-[200px] relative">
                         <div className="w-full aspect-square relative">
                            <ImageUploader 
                                id="style-uploader"
                                title="Style Image"
                                images={project.styleImage ? [project.styleImage] : []}
                                onFileUpload={handleSingleFileUpload}
                                onRemove={handleRemoveStyleImage}
                                onImageUpdate={handleUpdateStyleImage}
                            />
                             {(project.uploadingTarget === 'style' || project.isAnalyzingStyle) && (
                                <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center rounded-xl backdrop-blur-sm pointer-events-none z-20">
                                    <div className="animate-spin rounded-full h-6 w-6 border-t-2 border-b-2 border-[var(--color-accent)]"></div>
                                    <p className="text-xs text-[var(--color-text-base)] mt-2">{project.uploadingTarget === 'style' ? 'Processing...' : 'Analyzing...'}</p>
                                </div>
                            )}
                         </div>
                    </div>
                </div>
            </div>

            {/* 2. Options */}
            <CustomizationPanel
                options={project.options}
                setOptions={(newOptions) => updateActiveProjectState(p => { p.options = newOptions; })}
            />

            {/* 3. Prompt */}
            <PromptEditor
                prompt={project.prompt}
                setPrompt={handleSetPrompt}
                isAutoGenerated={project.isPromptAutoGenerated}
                onResetPrompt={handleResetPrompt}
                translatedPrompt={project.translatedPrompt}
                isTranslating={project.isTranslating}
                onUseTranslation={handleUseTranslation}
            />

             {/* 4. Action Button */}
            <div className="w-full">
                <button
                    onClick={handleGenerate}
                    disabled={project.isLoading || project.isEditing || !project.prompt || project.isAnalyzingStyle || !!project.uploadingTarget}
                    className="w-full bg-gradient-to-r from-[var(--color-accent)] to-[var(--color-accent-dark)] hover:from-[var(--color-accent-dark)] hover:to-[var(--color-accent-darker)] text-[var(--color-text-base)] font-bold py-4 px-8 rounded-xl text-xl transition-all duration-300 ease-in-out disabled:opacity-50 disabled:cursor-not-allowed shadow-xl hover:shadow-2xl hover:shadow-[var(--color-accent)]/20 disabled:shadow-none transform hover:-translate-y-1 disabled:transform-none"
                >
                    {project.isAnalyzingStyle ? 'Analyzing Style...' : project.uploadingTarget ? 'Processing Image...' : project.isLoading ? 'Generating...' : 'Generate Image'}
                </button>
            </div>
            
            {/* 5. Prompt Suggestions - Moved Here */}
            <PromptSuggestions 
                setPrompt={handleSetPrompt} 
                currentPrompt={project.prompt} 
            />

            {project.error && <div className="bg-[rgba(var(--color-accent-rgb),0.2)] border border-[rgba(var(--color-accent-rgb),0.5)] text-[var(--color-accent-light)] px-4 py-3 rounded-lg text-sm" role="alert">{project.error}</div>}
            
        </div>

        {/* --- RIGHT COLUMN: RESULT (Static) --- */}
        <div className="flex flex-col gap-4 pb-4 order-2">
             <div className="glass-card rounded-2xl p-4 flex flex-col">
                <h3 className="text-xl font-bold text-[var(--color-text-base)] mb-4">Result</h3>
                <div className="flex-grow flex flex-col justify-center min-h-[300px]">
                    <ResultDisplay 
                        imageFile={project.generatedImage}
                        isLoading={project.isLoading}
                        isEditing={project.isEditing}
                        editPrompt={project.editPrompt}
                        setEditPrompt={(prompt) => updateActiveProjectState(p => { p.editPrompt = prompt; })}
                        onImageEdit={handleImageEdit}
                    />
                </div>
             </div>
             {/* 6. History (Below Results) */}
            <HistoryPanel history={project.history} onSelect={handleHistorySelectImage} />
        </div>
    </main>
  );
};

export default CreatorStudio;
