
import React, { useState, useRef, useEffect } from 'react';

interface PromptEditorProps {
  prompt: string;
  setPrompt: (prompt: string) => void;
  isAutoGenerated: boolean;
  onResetPrompt: () => void;
  translatedPrompt: string | null;
  isTranslating: boolean;
  onUseTranslation: (translatedText: string) => void;
}

const SparkleIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" viewBox="0 0 20 20" fill="currentColor">
        <path fillRule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 11-2 0V6H3a1 1 0 110-2h1V3a1 1 0 011-1zm12 10a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1zM10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm0 14a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM4.156 5.156a1 1 0 011.414-1.414l.707.707a1 1 0 01-1.414 1.414l-.707-.707zm11.314 11.314a1 1 0 011.414-1.414l.707.707a1 1 0 01-1.414 1.414l-.707-.707zm-8.485 2.122a1 1 0 01-1.414 1.414l-.707-.707a1 1 0 011.414-1.414l.707.707zM15.844 5.156a1 1 0 011.414 1.414l-.707.707a1 1 0 01-1.414-1.414l.707-.707z" clipRule="evenodd" />
    </svg>
);

const CopyIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
    </svg>
);

const SwapIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
    </svg>
);

const TranslationSpinner = () => (
    <div className="animate-spin rounded-full h-4 w-4 border-t-2 border-b-2 border-[var(--color-accent)]"></div>
);

const SuggestionsDropdown: React.FC<{
    options: string[];
    onSelect: (value: string) => void;
    currentValue: string;
}> = ({ options, onSelect, currentValue }) => {
    const [isOpen, setIsOpen] = useState(false);
    const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    const displayValue = options.includes(currentValue) ? currentValue : "Select a suggestion...";

    return (
        <div className="relative w-full" ref={containerRef}>
            <button
                onClick={() => setIsOpen(!isOpen)}
                className={`w-full text-left appearance-none bg-black/20 border text-[var(--color-text-base)] rounded-xl px-4 py-3 pr-10 outline-none transition-all text-sm font-medium flex items-center justify-between
                ${isOpen 
                    ? 'border-[var(--color-accent)] ring-2 ring-[var(--color-accent)] bg-[rgba(var(--color-accent-rgb),0.05)]' 
                    : 'border-[rgba(var(--color-text-base-rgb),0.1)] hover:border-[var(--color-accent)]'
                }`}
            >
                <span className="truncate block w-full">{displayValue}</span>
                <svg xmlns="http://www.w3.org/2000/svg" className={`h-5 w-5 text-[var(--color-accent)] transition-transform duration-200 absolute right-3 top-1/2 -translate-y-1/2 flex-shrink-0 ${isOpen ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                </svg>
            </button>

            {isOpen && (
                <div className="absolute top-full left-0 mt-2 w-full bg-black/90 backdrop-blur-md border border-[rgba(var(--color-text-base-rgb),0.1)] rounded-xl shadow-2xl z-50 max-h-60 overflow-y-auto suggestions-scrollbar animate-in fade-in zoom-in-95 duration-100 origin-top">
                    {options.map((opt, idx) => (
                        <div
                            key={idx}
                            onClick={() => {
                                onSelect(opt);
                                setIsOpen(false);
                            }}
                            className={`px-4 py-3 text-sm cursor-pointer transition-colors border-b border-white/5 last:border-0
                                ${opt === currentValue 
                                    ? 'text-[var(--color-accent)] font-bold bg-[rgba(var(--color-accent-rgb),0.1)]' 
                                    : 'text-[var(--color-text-base)] hover:bg-[var(--color-accent)] hover:text-white'
                                }`}
                        >
                            {opt}
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export const PromptSuggestions: React.FC<{ setPrompt: (prompt: string) => void; currentPrompt: string }> = ({ setPrompt, currentPrompt }) => {
  const suggestedPrompts = [
    "Make it semi-reference and add a professional, symmetrical, and cinematic touch to it.",
    "make person/product in the place in Reference with mood and lighting cinematic",
    "Place the product in the reference scene with cinematic lighting and a dramatic mood.",
    "Create a professional product shot. Use the style reference for environment, and apply golden hour lighting.",
    "Generate a photo of the subject, matching the style reference's location. The lighting should be soft and natural."
  ];

  return (
      <div className="glass-card rounded-2xl p-4 flex flex-col gap-2 relative z-10">
        <h3 className="text-sm font-semibold text-[var(--color-text-medium)]">Suggestions</h3>
        <SuggestionsDropdown 
            options={suggestedPrompts} 
            onSelect={setPrompt} 
            currentValue={currentPrompt} 
        />
      </div>
  );
};

const PromptEditor: React.FC<PromptEditorProps> = ({ prompt, setPrompt, isAutoGenerated, onResetPrompt, translatedPrompt, isTranslating, onUseTranslation }) => {
  return (
    <div className="glass-card rounded-2xl p-4 flex flex-col gap-4">
      <div className="flex justify-between items-center">
        <h2 className="text-xl font-bold text-[var(--color-text-base)]">Edit Your Prompt</h2>
        <button
            onClick={onResetPrompt}
            disabled={isAutoGenerated}
            className="flex items-center text-sm px-3 py-1.5 rounded-md bg-[rgba(var(--color-text-base-rgb,229,231,206),0.05)] hover:bg-[rgba(var(--color-text-base-rgb,229,231,206),0.1)] disabled:bg-transparent text-[var(--color-accent-light)] hover:text-[var(--color-text-base)] disabled:text-[var(--color-text-muted)] disabled:cursor-not-allowed transition-all font-semibold"
            title="Reset to the automatically generated prompt"
        >
            <SparkleIcon />
            Reset to Auto-prompt
        </button>
      </div>
       <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        rows={6}
        className="w-full glass-input rounded-md p-3 text-sm leading-relaxed transition-all"
        placeholder="Your generated prompt will appear here..."
      />
      
      {(isTranslating || translatedPrompt) && (
        <div className="mt-2 p-4 glass-input rounded-lg bg-black/20">
            <div className="flex justify-between items-center mb-2">
            <h4 className="text-sm font-semibold text-[var(--color-text-medium)]">English Translation</h4>
            {isTranslating && <TranslationSpinner />}
            </div>
            {translatedPrompt && !isTranslating && (
            <>
                <p className="text-sm text-[var(--color-text-base)] leading-relaxed font-mono">{translatedPrompt}</p>
                <div className="flex items-center gap-2 mt-3">
                <button
                    onClick={() => onUseTranslation(translatedPrompt)}
                    className="flex items-center text-xs px-3 py-1.5 rounded-md bg-[rgba(var(--color-accent-rgb),0.2)] hover:bg-[rgba(var(--color-accent-rgb),0.4)] text-[var(--color-accent-light)] hover:text-[var(--color-text-base)] transition-colors font-semibold"
                >
                    <SwapIcon />
                    Use Translation
                </button>
                <button
                    onClick={() => navigator.clipboard.writeText(translatedPrompt)}
                    className="flex items-center text-xs px-3 py-1.5 rounded-md bg-[rgba(var(--color-text-base-rgb,229,231,206),0.05)] hover:bg-[rgba(var(--color-text-base-rgb,229,231,206),0.1)] text-[var(--color-text-medium)] hover:text-[var(--color-text-base)] transition-colors font-semibold"
                >
                    <CopyIcon />
                    Copy
                </button>
                </div>
            </>
            )}
        </div>
      )}
    </div>
  );
};

export default PromptEditor;
