
export interface Feature {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
}

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  content: string;
  avatar: string;
}

export interface AppScreenshot {
  id: string;
  url: string;
  caption: string;
  type: 'editor' | 'dashboard' | 'mobile';
}

export interface NoteAssistantState {
  input: string;
  output: string;
  isLoading: boolean;
  error: string | null;
}

// --- Image and Media Types ---

export interface ImageFile {
  base64: string;
  mimeType: string;
  name: string;
}

export interface AudioFile {
  base64: string;
  mimeType: string;
}

// --- Common UI Types ---

export type LightingStyle = 'Natural Light' | 'Studio Light' | 'Golden Hour' | 'Blue Hour' | 'Cinematic' | 'Dramatic';
export type CameraPerspective = 'Front View' | 'Top View' | 'Side View' | '45° Angle' | 'Close-up' | 'Macro Shot';
export type AspectRatio = '1:1' | '16:9' | '9:16' | '4:3' | '3:4';

export interface CustomizationOptions {
  lightingStyle: LightingStyle;
  cameraPerspective: CameraPerspective;
}

export interface HistoryItem {
  image: ImageFile;
  prompt: string;
}

// --- Creator Studio Types ---

export interface CreatorStudioProject {
  id: string;
  name: string;
  productImages: ImageFile[];
  styleImage: ImageFile | null;
  styleDescription: string | null;
  options: CustomizationOptions;
  prompt: string;
  isPromptAutoGenerated: boolean;
  translatedPrompt: string | null;
  isTranslating: boolean;
  generatedImage: ImageFile | null;
  history: HistoryItem[];
  isLoading: boolean;
  isEditing: boolean;
  isAnalyzingStyle: boolean;
  error: string | null;
  uploadingTarget: 'product' | 'style' | null;
  editPrompt: string;
}

// --- Photoshoot Director Types ---

export type ShotType = string;

export interface PhotoshootResult {
  shotType: ShotType;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
  editPrompt: string;
  isEditing: boolean;
}

export interface PhotoshootDirectorProject {
  id: string;
  name: string;
  productImages: ImageFile[];
  selectedShotTypes: ShotType[];
  customStylePrompt: string;
  results: PhotoshootResult[];
  isGenerating: boolean;
  isUploading: boolean;
  error: string | null;
}

// --- Prompt Studio Types ---

export interface PromptStudioHistoryItem {
  image: ImageFile;
  instructions: string;
  generatedPrompt: string;
}

export interface PromptStudioProject {
  id: string;
  name: string;
  images: ImageFile[];
  instructions: string;
  generatedPrompt: string | null;
  history: PromptStudioHistoryItem[];
  isLoading: boolean;
  isUploading: boolean;
  error: string | null;
}

// --- Voice Over Studio Types ---

export interface VoiceOverHistoryItem {
  audio: AudioFile;
  text: string;
  style: string;
  voice: string;
}

export interface VoiceOverStudioProject {
  id: string;
  name: string;
  text: string;
  styleInstructions: string;
  selectedVoice: string;
  voiceGenderFilter: 'All' | 'Male' | 'Female';
  generatedAudio: AudioFile | null;
  history: VoiceOverHistoryItem[];
  isLoading: boolean;
  isPlaying: boolean;
  previewLoadingVoice: string | null;
  previewPlayingVoice: string | null;
  error: string | null;
}

// --- Branding Studio Types ---

export type BrandingResultCategory = string;

export interface BrandingResult {
  category: BrandingResultCategory;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
  editPrompt: string;
  isEditing: boolean;
}

export interface BrandingStudioProject {
  id: string;
  name: string;
  logo: ImageFile | null;
  colors: string[];
  results: BrandingResult[];
  aspectRatio: AspectRatio;
  isUploading: boolean;
  isAnalyzing: boolean;
  isGenerating: boolean;
  error: string | null;
}

// --- Controller Studio Types ---

export type ControlCategory = 'Face' | 'Head' | 'Body' | 'Retouch';

export interface ControllerSlider {
  id: string;
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  category: ControlCategory;
}

export interface ControllerStudioProject {
  id: string;
  name: string;
  sourceImage: ImageFile | null;
  generatedImage: ImageFile | null;
  sliders: ControllerSlider[];
  activeCategory: ControlCategory;
  history: HistoryItem[];
  isUploading: boolean;
  isGenerating: boolean;
  error: string | null;
}

// --- Campaign Studio Types ---

export type CampaignScenario = string;

export interface CampaignResult {
  scenario: CampaignScenario;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
  editPrompt: string;
  isEditing: boolean;
}

export interface CampaignStudioProject {
  id: string;
  name: string;
  productImages: ImageFile[];
  productAnalysis: string | null;
  mode: 'auto' | 'custom';
  selectedMood: string;
  customPrompt: string;
  customIdeas: string[];
  results: CampaignResult[];
  isUploading: boolean;
  isAnalyzing: boolean;
  isGenerating: boolean;
  error: string | null;
}
